
["Pathing Cost Modifier #寻路Cost相关设置#"]

	["Pathing Cost Modifier #寻路Cost相关设置#"."Multiplier #乘子系数#"]
		#Rail path cost multiplier (default: 0.1, original:0.1) #铁轨Cost乘数 (默认 : 0.1 殖民地原设置 : 0.1)#
		#Range: 0.0 ~ 2.0
		railCostMultiplier = 0.1
		#Road path cost multiplier (default: 0.4, original:1/6) #路径Cost乘数 (默认 : 0.4 殖民地原设置 : 1/6)#
		#Range: 0.0 ~ 2.0
		roadCostMultiplier = 0.4
		#Drop cost multiplier (default: 1.0, original:1.0) #掉落Cost乘数 (默认 : 1.0 殖民地原设置 : 1.0)#
		#Notice: The base formula for falling cost has been modified from |dY|³ to (|dY| - 2/5)³ - 8/125. #注意:下落Cost基础公式已经从|dY|³修改为(|dY|-2/5)³-8/125.#
		#Range: 0.0 ~ 10.0
		dropCostMultiplier = 1.0

	["Pathing Cost Modifier #寻路Cost相关设置#"."Basic Cost Definer #基础Cost定义#"]
		#Water path cost addon (default: 8.0, original:2.0) #水路Cost (默认 : 8.0 殖民地原设置 : 2.0)#
		#Range: 0.0 ~ 24.0
		waterCostAddon = 8.0
		#Jump cost addon (default: 2.0, original:2.0) #跳跃(准确来说是非梯子爬升)Cost (默认 : 2.0 殖民地原设置 : 2.0)#
		#Range: 0.0 ~ 24.0
		jumpCostAddon = 2.0
		#In shape cost addon (default: 2.0, original:2.0) #实体方块内部行走的Cost (默认 : 2.0 殖民地原设置 : 2.0)#
		#Range: 0.0 ~ 24.0
		inShapeCostAddon = 2.0
		#Door and trapdoor’s cost addon (default: 3.0, original:3.0) #穿过各种"门"的Cost (默认 : 3.0 殖民地原设置 : 3.0)#
		#Range: 0.0 ~ 24.0
		doorsCostAddon = 3.0
		#Dive cost addon (default: 24.0, original:4.0) #潜水(潜多了会淹死)的Cost (默认 : 24.0 殖民地原设置 : 4.0)#
		#Range: 0.0 ~ 24.0
		diveCostAddon = 24.0
		#Breathing cave air cost addon (default: 0.3, original:3.0) #钻洞(人工的也算)的Cost,(默认 : 0.3 殖民地原设置 : 3.0)#
		#Range: 0.0 ~ 24.0
		caveCostAddon = 0.3
		#Exit railway cost addon (default: 4.0, original:4.0) #下铁路(人工的也算)的Cost(探测铁轨为”站点“，不计cost) (默认 : 4.0 殖民地原设置 : 4.0)#
		#Range: 0.0 ~ 24.0
		railExitAddon = 2.0

	["Pathing Cost Modifier #寻路Cost相关设置#"."Typical Cost Definer #针对性Cost定义#"]
		#Walk into panel cost addon (default: 4.0) #走在面板方块中(会不停的跳)的Cost (默认 : 4.0)#
		#Range: 0.0 ~ 24.0
		panelCostAddon = 4.0
		#Walk on shingle cost addon (default: 3.0, original:3.0) #上房揭瓦(走在屋瓦上)的Cost (默认 : 3.0 殖民地原设置 : 3.0)#
		#Range: 0.0 ~ 24.0
		shingleCostAddon = 3.0
		#Jump in farmland or drop onto farmland cost addon (default: 8.0) #在农田中跳上跳下的Cost (默认 : 8.0)#
		#Range: 0.0 ~ 24.0
		farmlandCostAddon = 8.0
		#Walk on leaves cost addon (default: 4.0) #爬树(走在树叶上)的Cost (默认 : 4.0)#
		#Range: 0.0 ~ 24.0
		leafCostAddon = 4.0
		#Walk in sweet berry bush cost addon (default: 24.0) #被浆果丛扎的Cost (默认 : 24.0)#
		#Range: 0.0 ~ 24.0
		berryCostAddon = 24.0

	["Pathing Cost Modifier #寻路Cost相关设置#"."Advanced Pathfinding Constant Definer #进阶寻路算法常数定义(警告：慎重修改！会对全局寻路产生极大影响！)#"]
		#When traversing callback nodes, there is a heuristic reduction on artificial roads. This value is used to control the rate at which the heuristic for railway callback nodes increases, and its formula is: RAIL_COST_MULTIPLIER * ONRAIL_CALLBACK_MULTIPLIER (default: 1.0) 
		#走回头路(其节点暂定义为回扣节点)时在人工道路上会有启发值减免,这是用来控制铁路回扣节点启发值增加速度的数值，其算式为 RAIL_COST_MULTIPLIER * ONRAIL_CALLBACK_MULTIPLIER (默认 : 1.0)
		#Range: 0.0 ~ 2.0
		onRailCallbackMutiplier = 1.0
		#This value is used to control the rate at which the heuristic for callback nodes on road blocks increases, and its formula is: ROAD_COST_MULTIPLIER * ONROAD_CALLBACK_MULTIPLIER (default: 1.2) 
		#用来控制道路方块上回扣节点启发值增加速度的数值，其算式为 ROAD_COST_MULTIPLIER * ONROAD_CALLBACK_MULTIPLIER (默认 : 1.2)
		#Range: 0.0 ~ 2.0
		onRoadCallbackMutiplier = 1.2
		#This is a global heuristic reduction, representing how much villagers prefer railways when pathfinding far away from the target point. The smaller the value, the stronger the preference. (default: 0.85)
		#是一个全局的启发值减免，表现为村民在远离目标点处寻路时对铁路的信任程度，数值越小越信任(默认 : 0.85)
		#Range: 0.5 ~ 2.0
		onRailPreference = 0.85
		#This is a global heuristic reduction, representing how much villagers prefer path blocks when pathfinding far away from the target point. The smaller the value, the stronger the preference. (default: 0.92)
		#是一个全局的启发值减免，表现为村民在远离目标点处寻路时对道路方块的信任程度，数值越小越信任(默认 : 0.92)
		#Range: 0.5 ~ 2.0
		onRoadPreference = 0.92
		#Tolerates how many times callback nodes can be expanded during each pathfinding process. (default: 2) #能容忍每次寻路中回扣节点被扩展几次，数值过大可能会造成扩展的无用节点增加 (默认 : 2)#
		#Range: 1 ~ 25
		callbackTimesTolerance = 2

["Basic Logic Modifier #基础逻辑修改#"]
	#Max pathing distance (default: 1000, original:500) 市民最大寻路距离,(默认 : 1000 殖民地原设置 : 500)
	#Range: 500 ~ 4095
	pathingDistance = 1000
	#Max animal modifier, would you like to modify the max animals to 2^(building level)? (default: false)
	# 养殖场最大生物数是否改为 2^建筑等级 原为 2*建筑等级(动物数目过大会导致卡顿，所以不默认开启),(默认 : false)
	increaceMaxAnimal = false
	#Lumberjcak will start to work only if hut is placed.
	# 伐木工会在放置工作方块后立即开始工作 (功能在后期有些超模，建议仅在前期开启以分担少量工作量)。
	lumberjackWorkWhenUnconstructed = false

["Restaurant Related Modifier #餐厅相关逻辑修改#"]
	#Duration citizens wait in the restaurant for cook service (minutes) (default: 0.5, original: 2.0)
	#你的村民在餐厅等待厨师服务的时间(分钟) (默认 : 0.5 殖民地原设置 : 2.0)
	#Range: 0.0 ~ 2.0
	restaurantWaitingTime = 0.5

["Hospital Related Modifier #医院相关逻辑修改#"]
	#The percentage of HP at which your citizens will seek treatment. (default: 0.2, original: 0.0)
	#你的村民将在剩多少比例的HP时去寻求医生治疗 (默认 : 0.2 殖民地原设置 : 0.0)
	#Range: 0.0 ~ 1.0
	curePercentageHP = 0.2
	#The absolute amount of HP at which your citizens will seek treatment. (default: 10.0, original: 6.0)
	#你的村民将在剩多少HP时去寻求医生治疗 (默认 : 10.0 殖民地原设置 : 6.0)
	#Range: 6.0 ~ 40.0
	cureHP = 10.0

